version: '3'

services:
  hypothesis_sqlalchemy-cpython:
    build:
      context: .
      args:
        - PYTHON_IMAGE=${CPYTHON_IMAGE_NAME}
        - PYTHON_IMAGE_VERSION=${CPYTHON_IMAGE_VERSION}
    image: lycantropos/hypothesis_sqlalchemy-cpython:0.3.1-alpha
    volumes:
      - ./hypothesis_sqlalchemy/:/opt/hypothesis_sqlalchemy/hypothesis_sqlalchemy/
      - ./tests/:/opt/hypothesis_sqlalchemy/tests/
      - ./README.md:/opt/hypothesis_sqlalchemy/README.md
      - ./requirements.txt:/opt/hypothesis_sqlalchemy/requirements.txt
      - ./requirements-tests.txt:/opt/hypothesis_sqlalchemy/requirements-tests.txt
      - ./setup.py:/opt/hypothesis_sqlalchemy/setup.py
      - ./setup.cfg:/opt/hypothesis_sqlalchemy/setup.cfg
    entrypoint: pytest
