version: '3'

services:
  hypothesis_sqlalchemy-pypy:
    build:
      context: .
      args:
        - PYTHON_IMAGE=${PYPY_IMAGE_NAME}
        - PYTHON_IMAGE_VERSION=${PYPY_IMAGE_VERSION}
    image: lycantropos/hypothesis_sqlalchemy-pypy:0.3.2-alpha
    volumes:
      - ./hypothesis_sqlalchemy/:/opt/hypothesis_sqlalchemy/hypothesis_sqlalchemy/
      - ./tests/:/opt/hypothesis_sqlalchemy/tests/
      - ./README.md:/opt/hypothesis_sqlalchemy/README.md
      - ./requirements.txt:/opt/hypothesis_sqlalchemy/requirements.txt
      - ./requirements-tests.txt:/opt/hypothesis_sqlalchemy/requirements-tests.txt
      - ./setup.py:/opt/hypothesis_sqlalchemy/setup.py
      - ./pytest.ini:/opt/hypothesis_sqlalchemy/pytest.ini
    entrypoint: pytest
